permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Patricia Danochristos"
  description: A portfolio website that showcases some of my best graphic design peices.
  font_url: "https://fonts.googleapis.com/css?family=Darker+Grotesque:300,500|Libre+Caslon+Display&display=swap"
  colors:
    background: "--color-neutral-grey"
    patterns:
      brand.logos: "--color-neutral-grey"
  rationales:
    typefaces.primary: |
      Darker Grotesque was selected because it is a simple and clean looking sans-serif typeface. This typeface adds simplicity to the design.
    typefaces.secondary: |
      Libre Caslon Display was selected for the headings of the website because it's modern serif typeface gives a contemporary feel to the website.
    colors.primary: |
      The primary colour is a muted grey, which grounds the text when paired with the more brighter and bolder accent colours.
    colors.secondary: |
      The secondary colours act as compliments to the primary colours by being bolder, brighter, and more inviting.
