title: "About"
description: |
  This page will give information on who I am, what inspires me, and a little bit more of my character.

patterns:
  about:
    title: "About"
    description: |
      The "about" page will outline information on who I am as a person and a designer.
    fields:
      - name: title
        type: string
        example: "Hello."
      - name: title-2
        type: string
        example: "[Say something about yourself in this bio!]"
      - name: content
        type: string
        example: "Surely, there must be a method to the daunting task of actually thinking about who I am as a person, right? Then explaining it to the general public? Meh, what have I got to lose. Here's the situation. My name is Patricia, and I am a student graphic designer based in Ottawa, Ontario. I have an INTENSE passion for solving problems in the most artistically original way. I do have a special place in my heart for web design, however, all aspects of graphic design give me a wonderful feeling inside. Throughout this website, you will be able to uncover some graphical pieces that I have completed throughout my student career."
      - name: image
        type: string
        example: "images/"
