title: "Sections"
description: |
  Sections are used on each case study page to organize content. Each section will have a unique peice of content, as well as images to show pregression of each project.

patterns:
  case-study-title:
    title: "Case Study Title"
    description: |
      The "case study title" section will display the name of the project, as well as the type of media the project was for (i.e. print, web, etc...)
    fields:
      - name: title
        type: string
        example: "Branding & Logo Design"
      - name: title-2
        type: string
        example: "The Greek Souvlaki Shack"
      - name: type
        type: string
        example: "Print & Web"
      - name: image
        type: string
        example: "/images/branding-mockup-2.jpg"
  case-study-overview:
    title: "Case Study Overview"
    description: |
      The "case study overview" section gives the user information on the background of the project, what was to be achieved, and the challenges.
    fields:
      - name: image-2
        type: string
        example: "/images/shop-logo-mockup.jpg"
      - name: subtitle-1
        type: string
        example: "Case Study Overview"
      - name: sub-subtitle-1
        type: string
        example: "Here's what we're working with"
      - name: subtitle-2
        type: string
        example: "Sketches"
      - name: subtitle-3
        type: string
        example: "Process & Challenges"
      - name: content-overview
        type: string
        example: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim."
  case-study-sketches:
    title: "Sketches"
    description: |
      The "case study sketches" section gives the user information on the ideation process, as well as imagery in terms of sketches.
    fields:
      - name: subtitle-2
        type: string
        example: "Ideation"
      - name: sub-subtitle-2
        type: string
        example: "Sketching sketches"
      - name: content-sketches
        type: string
        example: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim."
      - name: image-3
        type: string
        example: "/images/branding-sketches-1.jpg"
      - name: content-sketches-2
        type: string
        example: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
      - name: image-4
        type: string
        example: "/images/branding-sketches-2.jpg"
      - name: content-sketches-3
        type: string
        example: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
      - name: image-5
        type: string
        example: "/images/branding-sketches-3.jpg"
  case-study-final:
    title: "Final"
    description: |
      The "case study final" section gives the user information on the final outcome of the project.
    fields:
      - name: subtitle-4
        type: string
        example: "Outcome"
      - name: sub-subtitle-4
        type: string
        example: "Here's what the finished product looks like"
      - name: content-final
        type: string
        example: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim."
      - name: image-6
        type: string
        example: "/images/business-card-mockup.jpg"
      - name: image-7
        type: string
        example: "/images/label-tag-mockup.jpg"
      - name: image-8
        type: string
        example: "/images/branding-mockup-3.jpg"
  case-study-progress:
    title: "Progress"
    description: |
      The "case study progress" section gives the user information on the progress and objectives of the project.
    fields:
      - name: progress-title
        type: string
        example: "Progression"
      - name: swatches
        type: string
        example: "swatches.svg#cs1-1"
      - name: swatches-2
        type: string
        example: "swatches.svg#cs1-2"
      - name: swatch-title
        type: string
        example: Colour Palette
      - name: font
        type: string
        example: "swatches.svg#cs1-3"
      - name: font-2
        type: string
        example: "swatches.svg#cs1-4"
      - name: font-title
        type: string
        example: "Typography"
      - name: swatch-label
        type: string
        example: "#006088"
      - name: swatch-label-2
        type: string
        example: "#83AAB3"
