title: "Cards"
description: |
  Cards are used on the home page website to attract the user and send them to the case study for that particular peice.

patterns:
  case-study-card:
    title: "Case Sturdy Card"
    description: |
      The "case study" card sends the user to a detailed page of the steps taken in order to achieve final results of the selected case study. It includes a dramatic affect when hovered on.
    fields:
      - name: image
        type: string
        example: "branding-mockup.jpg"
      - name: url
        type: url
        example: "/link/"
