title: "Cards"
description: |
  Cards are used on the home page website to attract the user and send them to the case study for that particular peice.

patterns:
  case-study-card:
    title: "Case Study Card"
    description: |
      The "case study" card sends the user to a detailed page of the steps taken in order to achieve final results of the selected case study. It includes a dramatic affect when hovered on.
    fields:
      - name: image
        type: string
        example: "branding-mockup.jpg"
      - name: url
        type: url
        example: "/link/"
      - name: hover-image
        type: string
        example: "yellow-bg.svg"
      - name: hover-icon
        type: string
        example: "icons.svg#case-study-1-icon"
      - name: icon-label
        type: string
        example: "Branding & Logo Design"
